name: pytest

# Allows you to run this workflow manually from the Actions tab
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.8]
        rasa-version: [rasa, rasa3]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U ".[${{ matrix.rasa-version }}, spacy, develop, watson, telekom, fasttext, luis]"

    - name: Test with pytest
      run: pytest tests/ --ignore tests/test_watson_vendor.py
