name: pytest

# Allows you to run this workflow manually from the Actions tab
on:
  push:
    branch: [ feature/github_actions ]
  workflow_dispatch:

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    # at 4 am
#    - cron:  '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        rasa-version: [rasa, rasa3]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U ".[develop, watson]"

# , telekom, fasttext, luis, ${{ matrix.rasa-version }}, spacy

    - name: Test with pytest
      run: pytest tests/test_watson_vendor_mocked.py --ignore tests/test_watson_vendor.py
